"use client";

import Link from "next/link";
import { MoonieGoldSeal } from "@/components/moonie/MoonieGoldSeal";
import { MoonieAssistantTitle, MoonieVibeChips } from "@/components/moonie/MoonieDesk";
import { MOONIE_WIDGET_CHIPS, MOONIE_WIDGET_HELPER } from "@/lib/moonie/desk";
import { cn } from "@/lib/utils";

export function MoonieWidgetEmptyState({
  disabled,
  onSelect,
  hrefForPrompt,
  className,
  compact = false,
}: {
  disabled?: boolean;
  onSelect?: (prompt: string) => void;
  hrefForPrompt?: (prompt: string) => string;
  className?: string;
  /** Tighter spacing when shown above an active chat. */
  compact?: boolean;
}) {
  return (
    <div
      className={cn(
        "flex flex-col px-3",
        compact ? "pb-2 pt-1" : "pb-4 pt-3",
        className
      )}
    >
      <div className="flex flex-col items-center text-center">
        <MoonieGoldSeal
          size={compact ? "xs" : "sm"}
          variant="waving"
          context="chatEmpty"
          className={cn("mx-auto", compact ? "scale-[0.78]" : "scale-[0.82]")}
        />

        <div className={cn(compact ? "mt-2" : "mt-3")}>
          <h3>
            <MoonieAssistantTitle
              variant="paper"
              className={compact ? "!text-lg" : undefined}
            />
          </h3>
        </div>

        <p
          className={cn(
            "max-w-[14rem] text-xs leading-relaxed text-slate-500",
            compact ? "mt-1" : "mt-1.5"
          )}
        >
          {MOONIE_WIDGET_HELPER}
        </p>

        <MoonieVibeChips
          disabled={disabled}
          onSelect={onSelect}
          hrefForPrompt={hrefForPrompt}
          inline
          chips={MOONIE_WIDGET_CHIPS}
          className={cn(compact ? "mt-2" : "mt-3")}
        />

        <p
          className={cn(
            "mx-auto max-w-[16rem] text-center text-[10px] leading-relaxed text-slate-500",
            compact ? "mt-2.5" : "mt-4"
          )}
        >
          Recommendations are generated by AI from our catalogue. Some may miss
          the mark.{" "}
          <Link
            href="/content-guidelines"
            className="font-medium text-[#6E46C7] underline-offset-2 hover:underline"
          >
            Learn more
          </Link>
        </p>
      </div>
    </div>
  );
}
