/**
 * Curated English translations of Chinese web novels.
 * `externalLink` may still reference a community listing for editorial research,
 * but seed/import only persists OFFICIAL publisher URLs via verified-reading-links.
 */

export type TranslationSource =
  | "novelupdates"
  | "wuxiaworld"
  | "webnovel"
  | "qidian"
  | "volare";

export interface TranslatedCnNovel {
  title: string;
  author: string;
  genreSlug: string;
  tagSlugs: string[];
  externalLink: string;
  source: TranslationSource;
  /** Optional second genre */
  secondaryGenreSlug?: string;
  /**
   * Additional legitimate reading URLs (official publisher and/or NovelUpdates).
   * Never include pirate/mirror hosts.
   */
  extraLinks?: string[];
}

const nu = (slug: string) => `https://www.novelupdates.com/series/${slug}/`;
const ww = (slug: string) => `https://www.wuxiaworld.com/novel/${slug}`;
const wn = (bookId: string) => `https://www.webnovel.com/book/${bookId}`;

/** Popular English-translated Chinese web novels */
export const TRANSLATED_CN_NOVELS: TranslatedCnNovel[] = [
  // Xianxia / Xuanhuan
  {
    title: "Reverend Insanity",
    author: "Gu Zhen Ren",
    genreSlug: "xianxia",
    tagSlugs: ["cultivation", "earned-power", "character-driven"],
    externalLink: nu("reverend-insanity"),
    source: "novelupdates",
  },
  {
    title: "I Shall Seal the Heavens",
    author: "Er Gen",
    genreSlug: "xianxia",
    tagSlugs: ["cultivation", "earned-power"],
    externalLink: nu("i-shall-seal-the-heavens"),
    source: "novelupdates",
  },
  {
    title: "A Will Eternal",
    author: "Er Gen",
    genreSlug: "xianxia",
    secondaryGenreSlug: "comedy",
    tagSlugs: ["cultivation", "beginner-friendly"],
    externalLink: nu("a-will-eternal"),
    source: "novelupdates",
  },
  {
    title: "Renegade Immortal",
    author: "Er Gen",
    genreSlug: "xianxia",
    tagSlugs: ["cultivation", "earned-power"],
    externalLink: nu("renegade-immortal"),
    source: "novelupdates",
  },
  {
    title: "A Record of a Mortal's Journey to Immortality",
    author: "Wang Yu",
    genreSlug: "xianxia",
    tagSlugs: ["cultivation", "character-driven"],
    externalLink: nu("a-record-of-a-mortals-journey-to-immortality"),
    source: "novelupdates",
  },
  {
    title: "Pursuit of the Truth",
    author: "Er Gen",
    genreSlug: "xianxia",
    tagSlugs: ["cultivation", "earned-power"],
    externalLink: nu("pursuit-of-the-truth"),
    source: "novelupdates",
  },
  {
    title: "Coiling Dragon",
    author: "I Eat Tomatoes",
    genreSlug: "xianxia",
    tagSlugs: ["cultivation", "op-mc"],
    externalLink: ww("coiling-dragon"),
    source: "wuxiaworld",
    extraLinks: [nu("coiling-dragon")],
  },
  {
    title: "Desolate Era",
    author: "I Eat Tomatoes",
    genreSlug: "xianxia",
    tagSlugs: ["cultivation", "earned-power"],
    externalLink: ww("desolate-era"),
    source: "wuxiaworld",
    extraLinks: [nu("desolate-era")],
  },
  {
    title: "Stellar Transformations",
    author: "I Eat Tomatoes",
    genreSlug: "xianxia",
    tagSlugs: ["cultivation", "earned-power"],
    externalLink: ww("stellar-transformations"),
    source: "wuxiaworld",
    extraLinks: [nu("stellar-transformations")],
  },
  {
    title: "Swallowed Star",
    author: "I Eat Tomatoes",
    genreSlug: "sci-fi",
    secondaryGenreSlug: "xianxia",
    tagSlugs: ["earned-power", "op-mc"],
    externalLink: nu("swallowed-star"),
    source: "novelupdates",
  },
  {
    title: "Martial World",
    author: "Cocooned Cow",
    genreSlug: "xianxia",
    tagSlugs: ["cultivation", "op-mc"],
    externalLink: nu("martial-world"),
    source: "novelupdates",
  },
  {
    title: "True Martial World",
    author: "Cocooned Cow",
    genreSlug: "xianxia",
    tagSlugs: ["cultivation", "earned-power"],
    externalLink: nu("true-martial-world"),
    source: "novelupdates",
  },
  {
    title: "Perfect World",
    author: "Chen Dong",
    genreSlug: "xianxia",
    tagSlugs: ["cultivation", "earned-power"],
    externalLink: nu("perfect-world"),
    source: "novelupdates",
  },
  {
    title: "Battle Through the Heavens",
    author: "Tian Can Tu Dou",
    genreSlug: "xianxia",
    tagSlugs: ["cultivation", "op-mc"],
    externalLink: nu("battle-through-the-heavens"),
    source: "novelupdates",
  },
  {
    title: "Wu Dong Qian Kun",
    author: "Tian Can Tu Dou",
    genreSlug: "xianxia",
    tagSlugs: ["cultivation", "earned-power"],
    externalLink: nu("wu-dong-qian-kun"),
    source: "novelupdates",
  },
  {
    title: "Against the Gods",
    author: "Yun Qinghan",
    genreSlug: "xianxia",
    tagSlugs: ["cultivation", "op-mc"],
    externalLink: nu("against-the-gods"),
    source: "novelupdates",
  },
  {
    title: "A Martial Odyssey",
    author: "Edgar",
    genreSlug: "xianxia",
    tagSlugs: ["cultivation", "character-driven"],
    externalLink: nu("a-martial-odyssey"),
    source: "novelupdates",
  },
  {
    title: "Way of the Devil",
    author: "Get Together",
    genreSlug: "xianxia",
    tagSlugs: ["cultivation", "character-driven"],
    externalLink: nu("way-of-the-devil"),
    source: "novelupdates",
  },
  {
    title: "Martial Peak",
    author: "Momo",
    genreSlug: "xianxia",
    tagSlugs: ["cultivation", "earned-power"],
    externalLink: nu("martial-peak"),
    source: "novelupdates",
  },
  {
    title: "Spirit Realm",
    author: "Chen Dong",
    genreSlug: "xianxia",
    tagSlugs: ["cultivation", "character-driven"],
    externalLink: nu("spirit-realm"),
    source: "novelupdates",
  },
  {
    title: "Immortal Mortal",
    author: "Immortal Mortal",
    genreSlug: "xianxia",
    tagSlugs: ["cultivation", "beginner-friendly"],
    externalLink: nu("immortal-mortal"),
    source: "novelupdates",
  },
  {
    title: "Skyfire Avenue",
    author: "Tang Jia San Shao",
    genreSlug: "fantasy",
    tagSlugs: ["magic-academy", "character-driven"],
    externalLink: nu("skyfire-avenue"),
    source: "novelupdates",
  },
  {
    title: "Soul Land",
    author: "Tang Jia San Shao",
    genreSlug: "fantasy",
    tagSlugs: ["earned-power", "beginner-friendly"],
    externalLink: nu("douluo-dalu"),
    source: "novelupdates",
  },
  {
    title: "Heavenly Jewel Change",
    author: "Tang Jia San Shao",
    genreSlug: "fantasy",
    tagSlugs: ["earned-power", "character-driven"],
    externalLink: nu("heavenly-jewel-change"),
    source: "novelupdates",
  },
  {
    title: "Tales of Demons and Gods",
    author: "Mad Snail",
    genreSlug: "fantasy",
    tagSlugs: ["earned-power", "op-mc"],
    externalLink: nu("tales-of-demons-and-gods"),
    source: "novelupdates",
  },
  {
    title: "Apotheosis of Heroes",
    author: "Fang Xiang",
    genreSlug: "fantasy",
    tagSlugs: ["earned-power", "character-driven"],
    externalLink: nu("apotheosis-of-heroes"),
    source: "novelupdates",
  },
  {
    title: "Library of Heaven's Path",
    author: "Heng Sao Tian Ya",
    genreSlug: "fantasy",
    tagSlugs: ["op-mc", "beginner-friendly"],
    externalLink: nu("library-of-heavens-path"),
    source: "novelupdates",
  },
  {
    title: "Nightmare of the Gu",
    author: "Guan Zhi",
    genreSlug: "xianxia",
    tagSlugs: ["cultivation", "character-driven"],
    externalLink: nu("nightmare-of-the-gu"),
    source: "novelupdates",
  },
  {
    title: "Lord of the Mysteries",
    author: "Cuttlefish That Loves Diving",
    genreSlug: "fantasy",
    secondaryGenreSlug: "horror",
    tagSlugs: ["character-driven", "earned-power"],
    // Community listing; official English licensing varies by region.
    externalLink: nu("lord-of-the-mysteries"),
    source: "novelupdates",
  },
  {
    title: "Release That Witch",
    author: "Er Mu",
    genreSlug: "fantasy",
    tagSlugs: ["character-driven", "earned-power"],
    externalLink: nu("release-that-witch"),
    source: "novelupdates",
  },
  {
    title: "Warlock of the Magus World",
    author: "Bai Zhi Zhou",
    genreSlug: "fantasy",
    tagSlugs: ["earned-power", "character-driven"],
    externalLink: nu("warlock-of-the-magus-world"),
    source: "novelupdates",
  },
  {
    title: "The Legendary Mechanic",
    author: "Chocolion",
    genreSlug: "sci-fi",
    tagSlugs: ["earned-power", "character-driven"],
    externalLink: nu("the-legendary-mechanic"),
    source: "novelupdates",
  },
  {
    title: "The King's Avatar",
    author: "Butterfly Blue",
    genreSlug: "action",
    tagSlugs: ["character-driven", "earned-power"],
    externalLink: nu("the-kings-avatar"),
    source: "novelupdates",
  },
  {
    title: "Martial God Asura",
    author: "Kindhearted Bee",
    genreSlug: "xianxia",
    tagSlugs: ["cultivation", "op-mc"],
    externalLink: nu("martial-god-asura"),
    source: "novelupdates",
  },
  {
    title: "Ancient Strengthening Technique",
    author: "I Eat Tomatoes",
    genreSlug: "xianxia",
    tagSlugs: ["cultivation", "op-mc"],
    externalLink: nu("ancient-strengthening-technique"),
    source: "novelupdates",
  },
  {
    title: "Dragon-Marked War God",
    author: "Chen Xuan",
    genreSlug: "xianxia",
    tagSlugs: ["cultivation", "op-mc"],
    externalLink: nu("dragon-marked-war-god"),
    source: "novelupdates",
  },
  {
    title: "Emperor's Domination",
    author: "Yan Bi Xiao",
    genreSlug: "xianxia",
    tagSlugs: ["cultivation", "op-mc"],
    externalLink: nu("emperors-domination"),
    source: "novelupdates",
  },
  {
    title: "Beseech The Devil",
    author: "Er Gen",
    genreSlug: "xianxia",
    tagSlugs: ["cultivation", "character-driven"],
    externalLink: nu("beseech-the-devil"),
    source: "novelupdates",
  },
  {
    title: "The Invisible Dragon",
    author: "I Eat Tomatoes",
    genreSlug: "comedy",
    secondaryGenreSlug: "fantasy",
    tagSlugs: ["beginner-friendly", "character-driven"],
    externalLink: nu("the-invisible-dragon"),
    source: "novelupdates",
  },
  {
    title: "Godly Model Creator",
    author: "Two-Faced",
    genreSlug: "sci-fi",
    tagSlugs: ["earned-power", "op-mc"],
    externalLink: nu("godly-model-creator"),
    source: "novelupdates",
  },
  {
    title: "Sovereign of the Three Realms",
    author: "Plow Days",
    genreSlug: "xianxia",
    tagSlugs: ["cultivation", "earned-power"],
    externalLink: nu("sovereign-of-the-three-realms"),
    source: "novelupdates",
  },
  {
    title: "The Great Ruler",
    author: "Tian Can Tu Dou",
    genreSlug: "xianxia",
    tagSlugs: ["cultivation", "earned-power"],
    externalLink: nu("the-great-ruler"),
    source: "novelupdates",
  },
  {
    title: "The Nine Cauldrons",
    author: "I Eat Tomatoes",
    genreSlug: "xianxia",
    tagSlugs: ["cultivation", "earned-power"],
    externalLink: nu("the-nine-cauldrons"),
    source: "novelupdates",
  },
  {
    title: "A Step into the Past",
    author: "Huang Yi",
    genreSlug: "action",
    tagSlugs: ["character-driven", "earned-power"],
    externalLink: nu("a-step-into-the-past"),
    source: "novelupdates",
  },
  {
    title: "The Ultimate Student",
    author: "Ye Xuan",
    genreSlug: "action",
    tagSlugs: ["op-mc", "character-driven"],
    externalLink: nu("the-ultimate-student"),
    source: "novelupdates",
  },
  {
    title: "Long Live Summons",
    author: "Xia Bai",
    genreSlug: "fantasy",
    tagSlugs: ["op-mc", "beginner-friendly"],
    externalLink: nu("long-live-summons"),
    source: "novelupdates",
  },
  {
    title: "Bringing the Farm to Live in Another World",
    author: "Ming Yu",
    genreSlug: "fantasy",
    tagSlugs: ["beginner-friendly", "character-driven"],
    externalLink: nu("bringing-the-farm-to-live-in-another-world"),
    source: "novelupdates",
  },
  {
    title: "The Strongest System",
    author: "Echoing Blade",
    genreSlug: "fantasy",
    tagSlugs: ["op-mc", "beginner-friendly"],
    externalLink: nu("the-strongest-system"),
    source: "novelupdates",
  },
  {
    title: "My Wife is a Beautiful CEO",
    author: "Mo Mo",
    genreSlug: "romance",
    tagSlugs: ["character-driven", "slow-burn"],
    externalLink: nu("my-wife-is-a-beautiful-ceo"),
    source: "novelupdates",
  },
  {
    title: "Trial Marriage Husband: Need to Work Hard",
    author: "Tang Jia Shan Shao",
    genreSlug: "romance",
    tagSlugs: ["slow-burn", "character-driven"],
    externalLink: nu("trial-marriage-husband-need-to-work-hard"),
    source: "novelupdates",
  },
  {
    title: "Full Marks Hidden Marriage: Pick Up a Son Get a Free Husband",
    author: "Jing Ye",
    genreSlug: "romance",
    tagSlugs: ["slow-burn", "character-driven"],
    externalLink: nu("full-marks-hidden-marriage-pick-up-a-son-get-a-free-husband"),
    source: "novelupdates",
  },
  {
    title: "The Enchantress of Medicine",
    author: "Feng Jiu",
    genreSlug: "romance",
    secondaryGenreSlug: "fantasy",
    tagSlugs: ["slow-burn", "character-driven"],
    externalLink: nu("the-enchantress-of-medicine"),
    source: "novelupdates",
  },
  {
    title: "Poison Genius Consort",
    author: "Jie Mo",
    genreSlug: "romance",
    tagSlugs: ["slow-burn", "character-driven"],
    externalLink: nu("poison-genius-consort"),
    source: "novelupdates",
  },
  {
    title: "Genius Doctor: Black Belly Miss",
    author: "Good Morning",
    genreSlug: "romance",
    tagSlugs: ["op-mc", "character-driven"],
    externalLink: nu("genius-doctor-black-belly-miss"),
    source: "novelupdates",
  },
  {
    title: "The Demonic King Chases His Wife",
    author: "Su Su",
    genreSlug: "romance",
    tagSlugs: ["slow-burn", "character-driven"],
    externalLink: nu("the-demonic-king-chases-his-wife"),
    source: "novelupdates",
  },
  {
    title: "Quick Transmigration: Cannon Fodder's Record of Counterattacks",
    author: "Mu Dan",
    genreSlug: "romance",
    tagSlugs: ["character-driven", "beginner-friendly"],
    externalLink: nu("quick-transmigration-cannon-fodders-record-of-counterattacks"),
    source: "novelupdates",
  },
  {
    title: "The Untamed",
    author: "Mo Xiang Tong Xiu",
    genreSlug: "fantasy",
    tagSlugs: ["character-driven", "slow-burn"],
    externalLink: nu("grandmaster-of-demonic-cultivation"),
    source: "novelupdates",
  },
  {
    title: "Heaven Official's Blessing",
    author: "Mo Xiang Tong Xiu",
    genreSlug: "fantasy",
    tagSlugs: ["character-driven", "slow-burn"],
    externalLink: nu("heaven-officials-blessing"),
    source: "novelupdates",
  },
  {
    title: "Scum Villain's Self-Saving System",
    author: "Mo Xiang Tong Xiu",
    genreSlug: "fantasy",
    tagSlugs: ["character-driven", "slow-burn"],
    externalLink: nu("the-scum-villains-self-saving-system"),
    source: "novelupdates",
  },
  {
    title: "The Devil's Cage",
    author: "Zhai Zhu",
    genreSlug: "horror",
    tagSlugs: ["cosmic-horror", "character-driven"],
    externalLink: nu("the-devils-cage"),
    source: "novelupdates",
  },
  {
    title: "The Sacred Ruins",
    author: "Chen Dong",
    genreSlug: "sci-fi",
    tagSlugs: ["earned-power", "character-driven"],
    externalLink: nu("the-sacred-ruins"),
    source: "novelupdates",
  },
  {
    title: "The Three-Body Problem",
    author: "Liu Cixin",
    genreSlug: "sci-fi",
    tagSlugs: ["hard-sci-fi", "character-driven"],
    externalLink: nu("the-three-body-problem"),
    source: "novelupdates",
  },
  {
    title: "Super Gene",
    author: "Chen Xi",
    genreSlug: "sci-fi",
    tagSlugs: ["earned-power", "op-mc"],
    externalLink: nu("super-gene"),
    source: "novelupdates",
  },
  {
    title: "God-level Demon",
    author: "Great Lord of Cloudy Mountains",
    genreSlug: "litrpg",
    tagSlugs: ["dungeon-crawl", "op-mc"],
    externalLink: nu("god-level-demon"),
    source: "novelupdates",
  },
  {
    title: "Global Evolution: I Have an Attribute Board",
    author: "Cang Cong",
    genreSlug: "sci-fi",
    tagSlugs: ["earned-power", "op-mc"],
    externalLink: nu("global-evolution-i-have-an-attribute-board"),
    source: "novelupdates",
  },
  {
    title: "The Legend of Sun Knight",
    author: "Yu Wo",
    genreSlug: "comedy",
    secondaryGenreSlug: "fantasy",
    tagSlugs: ["character-driven", "beginner-friendly"],
    externalLink: nu("the-legend-of-sun-knight"),
    source: "novelupdates",
  },
  {
    title: "My Disciple Died Yet Again",
    author: "Yiyu Lu",
    genreSlug: "comedy",
    secondaryGenreSlug: "xianxia",
    tagSlugs: ["cultivation", "character-driven"],
    externalLink: nu("my-disciple-died-yet-again"),
    source: "novelupdates",
  },
  {
    title: "Cultivation Chat Group",
    author: "Holy Infant Huang Shang",
    genreSlug: "comedy",
    secondaryGenreSlug: "xianxia",
    tagSlugs: ["cultivation", "beginner-friendly"],
    externalLink: nu("cultivation-chat-group"),
    source: "novelupdates",
  },
  {
    title: "The Daily Life of the Immortal King",
    author: "Wang Yu",
    genreSlug: "comedy",
    secondaryGenreSlug: "fantasy",
    tagSlugs: ["op-mc", "beginner-friendly"],
    externalLink: nu("the-daily-life-of-the-immortal-king"),
    source: "novelupdates",
  },
  {
    title: "The Charm of Soul Pets",
    author: "Yu Jian",
    genreSlug: "fantasy",
    tagSlugs: ["earned-power", "character-driven"],
    externalLink: nu("the-charm-of-soul-pets"),
    source: "novelupdates",
  },
  {
    title: "The Legend of Futian",
    author: "Ouyang Fa",
    genreSlug: "xianxia",
    tagSlugs: ["cultivation", "earned-power"],
    externalLink: nu("the-legend-of-futian"),
    source: "novelupdates",
  },
  {
    title: "The Divine Nine-Dragon Cauldron",
    author: "Chen Mu",
    genreSlug: "xianxia",
    tagSlugs: ["cultivation", "op-mc"],
    externalLink: nu("the-divine-nine-dragon-cauldron"),
    source: "novelupdates",
  },
  {
    title: "The Invincible Dragon Emperor",
    author: "Chen Mu",
    genreSlug: "xianxia",
    tagSlugs: ["cultivation", "op-mc"],
    externalLink: nu("the-invincible-dragon-emperor"),
    source: "novelupdates",
  },
  {
    title: "The Strongest Abandoned Son",
    author: "Chen Mu",
    genreSlug: "xianxia",
    tagSlugs: ["cultivation", "earned-power"],
    externalLink: nu("the-strongest-abandoned-son"),
    source: "novelupdates",
  },
  {
    title: "The Strongest Gene",
    author: "Chen Xi",
    genreSlug: "sci-fi",
    tagSlugs: ["earned-power", "op-mc"],
    externalLink: nu("the-strongest-gene"),
    source: "novelupdates",
  },
  {
    title: "Shadow Slave",
    author: "Guiltythree",
    genreSlug: "fantasy",
    tagSlugs: ["earned-power", "character-driven"],
    externalLink: nu("shadow-slave"),
    source: "novelupdates",
  },
  {
    title: "Lord of Mysteries 2: Circle of Inevitability",
    author: "Cuttlefish That Loves Diving",
    genreSlug: "fantasy",
    tagSlugs: ["character-driven", "earned-power"],
    externalLink: nu("lord-of-mysteries-2-circle-of-inevitability"),
    source: "novelupdates",
  },
  {
    title: "Nirvana in Fire",
    author: "Hai Yan",
    genreSlug: "action",
    tagSlugs: ["character-driven", "earned-power"],
    externalLink: nu("nirvana-in-fire"),
    source: "novelupdates",
  },
  {
    title: "The Grandmaster Strategist",
    author: "Hai Yan",
    genreSlug: "action",
    tagSlugs: ["character-driven", "earned-power"],
    externalLink: nu("the-grandmaster-strategist"),
    source: "novelupdates",
  },
  {
    title: "Joy of Life",
    author: "Mao Ni",
    genreSlug: "action",
    tagSlugs: ["character-driven", "earned-power"],
    externalLink: nu("joy-of-life"),
    source: "novelupdates",
  },
  {
    title: "Evernight",
    author: "Guo Jing",
    genreSlug: "fantasy",
    tagSlugs: ["earned-power", "character-driven"],
    externalLink: nu("evernight"),
    source: "novelupdates",
  },
  {
    title: "The King's Avatar",
    author: "Butterfly Blue",
    genreSlug: "action",
    tagSlugs: ["character-driven", "earned-power"],
    externalLink: wn("the-king-s-avatar_203739"),
    source: "webnovel",
    extraLinks: [nu("the-kings-avatar")],
  },
  {
    title: "Martial God Asura",
    author: "Kindhearted Bee",
    genreSlug: "xianxia",
    tagSlugs: ["cultivation", "op-mc"],
    externalLink: wn("martial-god-asura_860891"),
    source: "webnovel",
    extraLinks: [nu("martial-god-asura")],
  },
  {
    title: "Spirit Vessel",
    author: "Jiao Sun",
    genreSlug: "xianxia",
    tagSlugs: ["cultivation", "earned-power"],
    externalLink: nu("spirit-vessel"),
    source: "novelupdates",
  },
  {
    title: "World of Cultivation",
    author: "Er Gen",
    genreSlug: "xianxia",
    tagSlugs: ["cultivation", "character-driven"],
    externalLink: nu("world-of-cultivation"),
    source: "novelupdates",
  },
  {
    title: "A Different Kind of Immortal",
    author: "Er Gen",
    genreSlug: "xianxia",
    tagSlugs: ["cultivation", "earned-power"],
    externalLink: nu("a-different-kind-of-immortal"),
    source: "novelupdates",
  },
];

export function getTranslatedCnCatalog(): TranslatedCnNovel[] {
  const seen = new Set<string>();
  return TRANSLATED_CN_NOVELS.filter((novel) => {
    const key = novel.title.toLowerCase();
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

export function sourceLabel(source: TranslationSource): string {
  switch (source) {
    case "novelupdates":
      return "NovelUpdates";
    case "wuxiaworld":
      return "Wuxiaworld";
    case "webnovel":
      return "Webnovel";
    case "qidian":
      return "Qidian International";
    case "volare":
      return "Volarenovels";
    default:
      return "Translation site";
  }
}
